### ISSUE TITLE
How to use left and right to control the path of the ball falling?

### ISSUE THREAD

**Issue by denzhe22** [AnsonH/plinko-game#7]
I found that the server of stake will control the initial position of the ball, and whether the landing point is left or right each time.  How should this be implemented?

**Comment by AnsonH** [comment]
Hi @denzhe22, thanks for stopping by 😄

In Stake's official implementation, they uses a server to generate a random seed (i.e. a random number) which decides the initial position of the ball. 

However, my implementation doesn't use any server to keep it simple. Hence, I use [this code](https://github.com/AnsonH/plinko-game/blob/main/src/lib/components/Plinko/PlinkoEngine.ts#L191-L194) to randomly generate the initial position. Here's a visualization of the code:

![image](https://github.com/AnsonH/plinko-game/assets/57580593/8135c13a-e3ff-4916-8060-39293206f44f)
